### ISSUE TITLE
The packaged exe crash when start

### ISSUE THREAD

**Issue by andyliu19851105** [fweidner/UE4-Plugin-SideBySide#1]
![game crshed](https://user-images.githubusercontent.com/2161283/30192151-322bdd38-9478-11e7-8d7f-6edc312c4367.png)

**Comment by fweidner** [comment]
When did this error happen? During startup of the engine or when you start a packaged project?

**Comment by Mbit555** [comment]
I have the same problem. Occurs when a packed game is started

**Comment by fweidner** [comment]
@andyliu19851105 @Mbit555 Thanks for mentioning it! I fixed it! There was an issue with the setup process. I updated the readme accordingly. You need to add the plugin as a module to you project.
